services:

  collector:
    image: otel/opentelemetry-collector-contrib:0.113.0
    ports:
      - "4317:4317" # OTLP gRPC receiver
    volumes:
      - ./config/collector/config.yaml:/etc/otelcol-contrib/config.yaml

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2
    ports:
      - "18888:18888" # Dashboard
      - "18889:18889" # OTLP gRPC
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
