services:

  collector:
    image: otel/opentelemetry-collector-contrib:0.113.0
    ports:
      - "4317:4317" # OTLP gRPC
      - "8889:8889" # Prometheus target
    volumes:
      - ./config/collector/config.yaml:/etc/otelcol-contrib/config.yaml

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.2
    ports:
      - "18888:18888" # Dashboard
      - "18889:18889" # OTLP gRPC
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090" # UI
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus/prometheus-data:/prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    ports:
      - "16686:16686" # UI
      - "4317" # OTLP gRPC
