receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  otlp/aspire:
    endpoint: http://aspire:18889
    tls:
      insecure: true
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true  
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire]
